[versions]
jacoco = "0.8.7"
micronaut = "4.5.0"
micronaut-gradle-plugin = "4.4.2"

[libraries]
# renovate hint
micronaut-platform = { module = "io.micronaut.platform:micronaut-platform", version.ref = "micronaut" }
gradle-plugin-micronaut = { group = "io.micronaut.gradle", name = "micronaut-platform-catalog-plugin", version.ref = "micronaut-gradle-plugin" }
gradle-plugin-release = { group = "pl.allegro.tech.build", name = "axion-release-plugin", version = "1.18.2" }
gradle-plugin-spotless = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version = "6.25.0" }

[plugins]
git-properties = { id = "com.gorylenko.gradle-git-properties", version = "2.4.2" }
micronaut-aot = { id = "io.micronaut.aot", version.ref = "micronaut-gradle-plugin" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronaut-gradle-plugin" }
micronaut-library = { id = "io.micronaut.library", version.ref = "micronaut-gradle-plugin" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }
